//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopWCFApp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ISearchByLastNameService")]
    public interface ISearchByLastNameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchByLastNameService/GetDataByLastName", ReplyAction="http://tempuri.org/ISearchByLastNameService/GetDataByLastNameResponse")]
        string GetDataByLastName(string lastName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearchByLastNameService/GetDataByLastName", ReplyAction="http://tempuri.org/ISearchByLastNameService/GetDataByLastNameResponse")]
        System.Threading.Tasks.Task<string> GetDataByLastNameAsync(string lastName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearchByLastNameServiceChannel : DesktopWCFApp.ServiceReference1.ISearchByLastNameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearchByLastNameServiceClient : System.ServiceModel.ClientBase<DesktopWCFApp.ServiceReference1.ISearchByLastNameService>, DesktopWCFApp.ServiceReference1.ISearchByLastNameService {
        
        public SearchByLastNameServiceClient() {
        }
        
        public SearchByLastNameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearchByLastNameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchByLastNameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearchByLastNameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDataByLastName(string lastName) {
            return base.Channel.GetDataByLastName(lastName);
        }
        
        public System.Threading.Tasks.Task<string> GetDataByLastNameAsync(string lastName) {
            return base.Channel.GetDataByLastNameAsync(lastName);
        }
    }
}
